<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class FrequencySeeder extends Seeder
{
    public function run(): void
    {
        $frequencies = [
            [
                'code' => 'ONCE',
                'name' => 'Una sola vez',
                'type' => 'one_time',
                'interval_value' => null,
                'interval_unit' => null,
                'times_per_period' => 1,
                'description' => 'Servicio que se ejecuta una sola vez y no se repite automáticamente.',
                'order' => 1,
            ],
            [
                'code' => 'DAILY',
                'name' => 'Diaria',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'day',
                'times_per_period' => 1,
                'description' => 'Servicio que se ejecuta una vez cada día.',
                'order' => 2,
            ],
            [
                'code' => 'TWICE_DAILY',
                'name' => 'Dos veces al día',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'day',
                'times_per_period' => 2,
                'description' => 'Servicio que se ejecuta dos veces durante el mismo día.',
                'order' => 3,
            ],
            [
                'code' => 'THREE_TIMES_DAILY',
                'name' => 'Tres veces al día',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'day',
                'times_per_period' => 3,
                'description' => 'Servicio que se ejecuta tres veces durante el mismo día.',
                'order' => 4,
            ],
            [
                'code' => 'EVERY_TWO_DAYS',
                'name' => 'Cada dos días',
                'type' => 'fixed',
                'interval_value' => 2,
                'interval_unit' => 'day',
                'times_per_period' => 1,
                'description' => 'Servicio que se ejecuta cada dos días.',
                'order' => 5,
            ],
            [
                'code' => 'EVERY_THREE_DAYS',
                'name' => 'Cada tres días',
                'type' => 'fixed',
                'interval_value' => 3,
                'interval_unit' => 'day',
                'times_per_period' => 1,
                'description' => 'Servicio que se ejecuta cada tres días.',
                'order' => 6,
            ],
            [
                'code' => 'WEEKLY',
                'name' => 'Semanal',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'week',
                'times_per_period' => 1,
                'description' => 'Servicio que se ejecuta una vez por semana.',
                'order' => 7,
            ],
            [
                'code' => 'TWICE_WEEKLY',
                'name' => 'Dos veces por semana',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'week',
                'times_per_period' => 2,
                'description' => 'Servicio que se ejecuta dos veces por semana.',
                'order' => 8,
            ],
            [
                'code' => 'THREE_TIMES_WEEKLY',
                'name' => 'Tres veces por semana',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'week',
                'times_per_period' => 3,
                'description' => 'Servicio que se ejecuta tres veces por semana.',
                'order' => 9,
            ],
            [
                'code' => 'FOUR_TIMES_WEEKLY',
                'name' => 'Cuatro veces por semana',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'week',
                'times_per_period' => 4,
                'description' => 'Servicio que se ejecuta cuatro veces por semana.',
                'order' => 10,
            ],
            [
                'code' => 'FIVE_TIMES_WEEKLY',
                'name' => 'Cinco veces por semana',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'week',
                'times_per_period' => 5,
                'description' => 'Servicio que se ejecuta cinco veces por semana.',
                'order' => 11,
            ],
            [
                'code' => 'BIWEEKLY',
                'name' => 'Quincenal',
                'type' => 'fixed',
                'interval_value' => 2,
                'interval_unit' => 'week',
                'times_per_period' => 1,
                'description' => 'Servicio que se ejecuta cada dos semanas.',
                'order' => 12,
            ],
            [
                'code' => 'EVERY_FIFTEEN_DAYS',
                'name' => 'Cada quince días',
                'type' => 'fixed',
                'interval_value' => 15,
                'interval_unit' => 'day',
                'times_per_period' => 1,
                'description' => 'Servicio que se ejecuta cada quince días.',
                'order' => 13,
            ],
            [
                'code' => 'MONTHLY',
                'name' => 'Mensual',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'month',
                'times_per_period' => 1,
                'description' => 'Servicio que se ejecuta una vez al mes.',
                'order' => 14,
            ],
            [
                'code' => 'TWICE_MONTHLY',
                'name' => 'Dos veces al mes',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'month',
                'times_per_period' => 2,
                'description' => 'Servicio que se ejecuta dos veces durante el mes.',
                'order' => 15,
            ],
            [
                'code' => 'THREE_TIMES_MONTHLY',
                'name' => 'Tres veces al mes',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'month',
                'times_per_period' => 3,
                'description' => 'Servicio que se ejecuta tres veces durante el mes.',
                'order' => 16,
            ],
            [
                'code' => 'BIMONTHLY',
                'name' => 'Bimestral',
                'type' => 'fixed',
                'interval_value' => 2,
                'interval_unit' => 'month',
                'times_per_period' => 1,
                'description' => 'Servicio que se ejecuta cada dos meses.',
                'order' => 17,
            ],
            [
                'code' => 'QUARTERLY',
                'name' => 'Trimestral',
                'type' => 'fixed',
                'interval_value' => 3,
                'interval_unit' => 'month',
                'times_per_period' => 1,
                'description' => 'Servicio que se ejecuta cada tres meses.',
                'order' => 18,
            ],
            [
                'code' => 'FOUR_TIMES_YEAR',
                'name' => 'Cuatro veces al año',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'year',
                'times_per_period' => 4,
                'description' => 'Servicio que se ejecuta cuatro veces durante el año.',
                'order' => 19,
            ],
            [
                'code' => 'SEMIANNUAL',
                'name' => 'Semestral',
                'type' => 'fixed',
                'interval_value' => 6,
                'interval_unit' => 'month',
                'times_per_period' => 1,
                'description' => 'Servicio que se ejecuta cada seis meses.',
                'order' => 20,
            ],
            [
                'code' => 'ANNUAL',
                'name' => 'Anual',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'year',
                'times_per_period' => 1,
                'description' => 'Servicio que se ejecuta una vez al año.',
                'order' => 21,
            ],
            [
                'code' => 'TWICE_YEAR',
                'name' => 'Dos veces al año',
                'type' => 'fixed',
                'interval_value' => 1,
                'interval_unit' => 'year',
                'times_per_period' => 2,
                'description' => 'Servicio que se ejecuta dos veces durante el año.',
                'order' => 22,
            ],
            [
                'code' => 'SEASONAL',
                'name' => 'Estacional',
                'type' => 'seasonal',
                'interval_value' => null,
                'interval_unit' => 'season',
                'times_per_period' => 1,
                'description' => 'Servicio que se ejecuta según una temporada o condición climática.',
                'order' => 23,
            ],
            [
                'code' => 'RAINY_SEASON',
                'name' => 'Temporada de lluvias',
                'type' => 'seasonal',
                'interval_value' => null,
                'interval_unit' => 'season',
                'times_per_period' => 1,
                'description' => 'Servicio programado durante la temporada de lluvias.',
                'order' => 24,
            ],
            [
                'code' => 'DRY_SEASON',
                'name' => 'Temporada seca',
                'type' => 'seasonal',
                'interval_value' => null,
                'interval_unit' => 'season',
                'times_per_period' => 1,
                'description' => 'Servicio programado durante la temporada seca.',
                'order' => 25,
            ],
            [
                'code' => 'BEFORE_EVENT',
                'name' => 'Antes de un evento',
                'type' => 'event_based',
                'interval_value' => null,
                'interval_unit' => null,
                'times_per_period' => 1,
                'description' => 'Servicio realizado antes de una actividad o evento comunitario.',
                'order' => 26,
            ],
            [
                'code' => 'AFTER_EVENT',
                'name' => 'Después de un evento',
                'type' => 'event_based',
                'interval_value' => null,
                'interval_unit' => null,
                'times_per_period' => 1,
                'description' => 'Servicio realizado después de una actividad o evento comunitario.',
                'order' => 27,
            ],
            [
                'code' => 'ON_DEMAND',
                'name' => 'Bajo demanda',
                'type' => 'on_demand',
                'interval_value' => null,
                'interval_unit' => null,
                'times_per_period' => 1,
                'description' => 'Servicio realizado cuando existe una solicitud o necesidad específica.',
                'order' => 28,
            ],
            [
                'code' => 'BY_REPORT',
                'name' => 'Por reporte ciudadano',
                'type' => 'on_demand',
                'interval_value' => null,
                'interval_unit' => null,
                'times_per_period' => 1,
                'description' => 'Servicio activado mediante un reporte o solicitud ciudadana.',
                'order' => 29,
            ],
            [
                'code' => 'BY_INSPECTION',
                'name' => 'Según inspección',
                'type' => 'conditional',
                'interval_value' => null,
                'interval_unit' => null,
                'times_per_period' => 1,
                'description' => 'Servicio programado según el resultado de una inspección técnica.',
                'order' => 30,
            ],
            [
                'code' => 'PREVENTIVE',
                'name' => 'Mantenimiento preventivo',
                'type' => 'conditional',
                'interval_value' => null,
                'interval_unit' => null,
                'times_per_period' => 1,
                'description' => 'Servicio programado para evitar fallas o deterioro.',
                'order' => 31,
            ],
            [
                'code' => 'CORRECTIVE',
                'name' => 'Mantenimiento correctivo',
                'type' => 'conditional',
                'interval_value' => null,
                'interval_unit' => null,
                'times_per_period' => 1,
                'description' => 'Servicio realizado para corregir una falla o daño existente.',
                'order' => 32,
            ],
            [
                'code' => 'EMERGENCY',
                'name' => 'Emergencia inmediata',
                'type' => 'emergency',
                'interval_value' => null,
                'interval_unit' => null,
                'times_per_period' => 1,
                'description' => 'Servicio que debe ejecutarse inmediatamente debido a un riesgo o emergencia.',
                'order' => 33,
            ],
            [
                'code' => 'WITHIN_24_HOURS',
                'name' => 'Dentro de 24 horas',
                'type' => 'response_time',
                'interval_value' => 24,
                'interval_unit' => 'hour',
                'times_per_period' => 1,
                'description' => 'Servicio que debe atenderse dentro de las siguientes 24 horas.',
                'order' => 34,
            ],
            [
                'code' => 'WITHIN_48_HOURS',
                'name' => 'Dentro de 48 horas',
                'type' => 'response_time',
                'interval_value' => 48,
                'interval_unit' => 'hour',
                'times_per_period' => 1,
                'description' => 'Servicio que debe atenderse dentro de las siguientes 48 horas.',
                'order' => 35,
            ],
            [
                'code' => 'WITHIN_SEVEN_DAYS',
                'name' => 'Dentro de siete días',
                'type' => 'response_time',
                'interval_value' => 7,
                'interval_unit' => 'day',
                'times_per_period' => 1,
                'description' => 'Servicio que debe atenderse dentro de los siguientes siete días.',
                'order' => 36,
            ],
        ];

        $now = now();

        $rows = collect($frequencies)
            ->map(function (array $frequency) use ($now): array {
                return [
                    'code' => $frequency['code'],
                    'name' => $frequency['name'],
                    'frequency_type' => $frequency['type'],
                    'interval_value' => $frequency['interval_value'],
                    'interval_unit' => $frequency['interval_unit'],
                    'times_per_period' => $frequency['times_per_period'],
                    'description' => $frequency['description'],
                    'sort_order' => $frequency['order'],
                    'active' => true,
                    'created_at' => $now,
                    'updated_at' => $now,
                ];
            })
            ->values()
            ->all();

        DB::table('frequencies')->upsert(
            $rows,
            ['code'],
            [
                'name',
                'frequency_type',
                'interval_value',
                'interval_unit',
                'times_per_period',
                'description',
                'sort_order',
                'active',
                'updated_at',
            ]
        );
    }
}
