/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AuditoriaEventosInterface extends Interface {
  getFunction(nameOrSignature: "registrarEvento"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "EventoRegistrado"): EventFragment;

  encodeFunctionData(
    functionFragment: "registrarEvento",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "registrarEvento",
    data: BytesLike
  ): Result;
}

export namespace EventoRegistradoEvent {
  export type InputTuple = [
    tipoEvento: BigNumberish,
    referenciaId: BigNumberish,
    dataHash: BytesLike,
    usuario: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    tipoEvento: bigint,
    referenciaId: bigint,
    dataHash: string,
    usuario: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    tipoEvento: bigint;
    referenciaId: bigint;
    dataHash: string;
    usuario: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AuditoriaEventos extends BaseContract {
  connect(runner?: ContractRunner | null): AuditoriaEventos;
  waitForDeployment(): Promise<this>;

  interface: AuditoriaEventosInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  registrarEvento: TypedContractMethod<
    [tipoEvento: BigNumberish, referenciaId: BigNumberish, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "registrarEvento"
  ): TypedContractMethod<
    [tipoEvento: BigNumberish, referenciaId: BigNumberish, dataHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "EventoRegistrado"
  ): TypedContractEvent<
    EventoRegistradoEvent.InputTuple,
    EventoRegistradoEvent.OutputTuple,
    EventoRegistradoEvent.OutputObject
  >;

  filters: {
    "EventoRegistrado(uint8,uint256,bytes32,address,uint256)": TypedContractEvent<
      EventoRegistradoEvent.InputTuple,
      EventoRegistradoEvent.OutputTuple,
      EventoRegistradoEvent.OutputObject
    >;
    EventoRegistrado: TypedContractEvent<
      EventoRegistradoEvent.InputTuple,
      EventoRegistradoEvent.OutputTuple,
      EventoRegistradoEvent.OutputObject
    >;
  };
}
