/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ContratoDistribucionInterface extends Interface {
  getFunction(
    nameOrSignature: "contratoExiste" | "registrarContrato"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ContratoRegistrado"): EventFragment;

  encodeFunctionData(
    functionFragment: "contratoExiste",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registrarContrato",
    values: [BytesLike, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "contratoExiste",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registrarContrato",
    data: BytesLike
  ): Result;
}

export namespace ContratoRegistradoEvent {
  export type InputTuple = [
    documentHash: BytesLike,
    numeroContrato: string,
    registradoPor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    documentHash: string,
    numeroContrato: string,
    registradoPor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    documentHash: string;
    numeroContrato: string;
    registradoPor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ContratoDistribucion extends BaseContract {
  connect(runner?: ContractRunner | null): ContratoDistribucion;
  waitForDeployment(): Promise<this>;

  interface: ContratoDistribucionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  contratoExiste: TypedContractMethod<
    [documentHash: BytesLike],
    [boolean],
    "view"
  >;

  registrarContrato: TypedContractMethod<
    [documentHash: BytesLike, numeroContrato: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "contratoExiste"
  ): TypedContractMethod<[documentHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registrarContrato"
  ): TypedContractMethod<
    [documentHash: BytesLike, numeroContrato: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ContratoRegistrado"
  ): TypedContractEvent<
    ContratoRegistradoEvent.InputTuple,
    ContratoRegistradoEvent.OutputTuple,
    ContratoRegistradoEvent.OutputObject
  >;

  filters: {
    "ContratoRegistrado(bytes32,string,address,uint256)": TypedContractEvent<
      ContratoRegistradoEvent.InputTuple,
      ContratoRegistradoEvent.OutputTuple,
      ContratoRegistradoEvent.OutputObject
    >;
    ContratoRegistrado: TypedContractEvent<
      ContratoRegistradoEvent.InputTuple,
      ContratoRegistradoEvent.OutputTuple,
      ContratoRegistradoEvent.OutputObject
    >;
  };
}
