/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as registrodocumentosSol from "./Registrodocumentos.sol";
export type { registrodocumentosSol };
export type { AuditoriaEventos } from "./AuditoriaEventos";
export type { ContratoDistribucion } from "./ContratoDistribucion";
export type { Counter } from "./Counter";
export type { MultaMunicipal } from "./MultaMunicipal";
export * as factories from "./factories";
export { AuditoriaEventos__factory } from "./factories/AuditoriaEventos__factory";
export { ContratoDistribucion__factory } from "./factories/ContratoDistribucion__factory";
export { Counter__factory } from "./factories/Counter__factory";
export { MultaMunicipal__factory } from "./factories/MultaMunicipal__factory";
export type { RegistroDocumentos } from "./Registrodocumentos.sol/RegistroDocumentos";
export { RegistroDocumentos__factory } from "./factories/Registrodocumentos.sol/RegistroDocumentos__factory";
