/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface MultaMunicipalInterface extends Interface {
  getFunction(
    nameOrSignature: "emitirMulta" | "multas" | "pagarMulta"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "emitirMulta",
    values: [AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "multas",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pagarMulta",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "emitirMulta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multas", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pagarMulta", data: BytesLike): Result;
}

export interface MultaMunicipal extends BaseContract {
  connect(runner?: ContractRunner | null): MultaMunicipal;
  waitForDeployment(): Promise<this>;

  interface: MultaMunicipalInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  emitirMulta: TypedContractMethod<
    [_infractor: AddressLike, _monto: BigNumberish, _motivo: string],
    [void],
    "nonpayable"
  >;

  multas: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, string, boolean] & {
        infractor: string;
        monto: bigint;
        fecha: bigint;
        motivo: string;
        pagada: boolean;
      }
    ],
    "view"
  >;

  pagarMulta: TypedContractMethod<[_id: BigNumberish], [void], "payable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "emitirMulta"
  ): TypedContractMethod<
    [_infractor: AddressLike, _monto: BigNumberish, _motivo: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "multas"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, string, boolean] & {
        infractor: string;
        monto: bigint;
        fecha: bigint;
        motivo: string;
        pagada: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "pagarMulta"
  ): TypedContractMethod<[_id: BigNumberish], [void], "payable">;

  filters: {};
}
