/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  AuditoriaEventos,
  AuditoriaEventosInterface,
} from "../AuditoriaEventos";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint8",
        name: "tipoEvento",
        type: "uint8",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "referenciaId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "dataHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "address",
        name: "usuario",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "EventoRegistrado",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint8",
        name: "tipoEvento",
        type: "uint8",
      },
      {
        internalType: "uint256",
        name: "referenciaId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "dataHash",
        type: "bytes32",
      },
    ],
    name: "registrarEvento",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101818061001f6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063fc2359ee14610030575b600080fd5b61004361003e366004610110565b610045565b005b60008360ff161161008d5760405162461bcd60e51b815260206004820152600d60248201526c5469706f20696e76616c69646f60981b60448201526064015b60405180910390fd5b806100ca5760405162461bcd60e51b815260206004820152600d60248201526c4861736820696e76616c69646f60981b6044820152606401610084565b604080513381524260208201528291849160ff8716917f6b952cf1d16116ed524b09e7902549d2690cd2d6f964c10b3b129e542bde5583910160405180910390a4505050565b60008060006060848603121561012557600080fd5b833560ff8116811461013657600080fd5b9560208501359550604090940135939250505056fea26469706673582212209b72e4302e24b2ddaac227bb71dd350ae96fcf619389cd91b81334ba8bf3c9c164736f6c634300081c0033";

type AuditoriaEventosConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: AuditoriaEventosConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class AuditoriaEventos__factory extends ContractFactory {
  constructor(...args: AuditoriaEventosConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      AuditoriaEventos & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): AuditoriaEventos__factory {
    return super.connect(runner) as AuditoriaEventos__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AuditoriaEventosInterface {
    return new Interface(_abi) as AuditoriaEventosInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): AuditoriaEventos {
    return new Contract(address, _abi, runner) as unknown as AuditoriaEventos;
  }
}
