/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type {
  ContratoDistribucion,
  ContratoDistribucionInterface,
} from "../ContratoDistribucion";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "documentHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "numeroContrato",
        type: "string",
      },
      {
        indexed: true,
        internalType: "address",
        name: "registradoPor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "ContratoRegistrado",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "documentHash",
        type: "bytes32",
      },
    ],
    name: "contratoExiste",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "documentHash",
        type: "bytes32",
      },
      {
        internalType: "string",
        name: "numeroContrato",
        type: "string",
      },
    ],
    name: "registrarContrato",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506102858061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80638f128a1b1461003b578063b7c716cb14610050575b600080fd5b61004e61004936600461017f565b610087565b005b61007361005e3660046101fd565b60009081526020819052604090205460ff1690565b604051901515815260200160405180910390f35b826100c95760405162461bcd60e51b815260206004820152600d60248201526c4861736820696e76616c69646f60981b60448201526064015b60405180910390fd5b60008381526020819052604090205460ff16156101215760405162461bcd60e51b8152602060048201526016602482015275436f6e747261746f207961207265676973747261646f60501b60448201526064016100c0565b60008381526020819052604090819020805460ff1916600117905551339084907f5172c518c08908115ecc926327cb7f87a59ccf21842718334d29b81a7af7668e9061017290869086904290610216565b60405180910390a3505050565b60008060006040848603121561019457600080fd5b83359250602084013567ffffffffffffffff8111156101b257600080fd5b8401601f810186136101c357600080fd5b803567ffffffffffffffff8111156101da57600080fd5b8660208284010111156101ec57600080fd5b939660209190910195509293505050565b60006020828403121561020f57600080fd5b5035919050565b604081528260408201528284606083013760006060848301015260006060601f19601f860116830101905082602083015294935050505056fea2646970667358221220fc599e76dbe21bdcf2bc2859ba8386ea34467e6124b23f2a7b83d9fc9bd5715b64736f6c634300081c0033";

type ContratoDistribucionConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ContratoDistribucionConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ContratoDistribucion__factory extends ContractFactory {
  constructor(...args: ContratoDistribucionConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ContratoDistribucion & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): ContratoDistribucion__factory {
    return super.connect(runner) as ContratoDistribucion__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ContratoDistribucionInterface {
    return new Interface(_abi) as ContratoDistribucionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ContratoDistribucion {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ContratoDistribucion;
  }
}
