/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as registrodocumentosSol from "./Registrodocumentos.sol";
export { AuditoriaEventos__factory } from "./AuditoriaEventos__factory";
export { ContratoDistribucion__factory } from "./ContratoDistribucion__factory";
export { Counter__factory } from "./Counter__factory";
export { MultaMunicipal__factory } from "./MultaMunicipal__factory";
