/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RegistroDocumentosInterface extends Interface {
  getFunction(
    nameOrSignature: "existe" | "registrarDocumento"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DocumentoRegistrado"): EventFragment;

  encodeFunctionData(functionFragment: "existe", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "registrarDocumento",
    values: [BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "existe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registrarDocumento",
    data: BytesLike
  ): Result;
}

export namespace DocumentoRegistradoEvent {
  export type InputTuple = [
    documentHash: BytesLike,
    documentId: BigNumberish,
    registradoPor: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    documentHash: string,
    documentId: bigint,
    registradoPor: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    documentHash: string;
    documentId: bigint;
    registradoPor: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RegistroDocumentos extends BaseContract {
  connect(runner?: ContractRunner | null): RegistroDocumentos;
  waitForDeployment(): Promise<this>;

  interface: RegistroDocumentosInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  existe: TypedContractMethod<[documentHash: BytesLike], [boolean], "view">;

  registrarDocumento: TypedContractMethod<
    [documentId: BigNumberish, documentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "existe"
  ): TypedContractMethod<[documentHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registrarDocumento"
  ): TypedContractMethod<
    [documentId: BigNumberish, documentHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DocumentoRegistrado"
  ): TypedContractEvent<
    DocumentoRegistradoEvent.InputTuple,
    DocumentoRegistradoEvent.OutputTuple,
    DocumentoRegistradoEvent.OutputObject
  >;

  filters: {
    "DocumentoRegistrado(bytes32,uint256,address,uint256)": TypedContractEvent<
      DocumentoRegistradoEvent.InputTuple,
      DocumentoRegistradoEvent.OutputTuple,
      DocumentoRegistradoEvent.OutputObject
    >;
    DocumentoRegistrado: TypedContractEvent<
      DocumentoRegistradoEvent.InputTuple,
      DocumentoRegistradoEvent.OutputTuple,
      DocumentoRegistradoEvent.OutputObject
    >;
  };
}
