/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  RegistroDocumentos,
  RegistroDocumentosInterface,
} from "../../Registrodocumentos.sol/RegistroDocumentos";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "documentHash",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "documentId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "registradoPor",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "timestamp",
        type: "uint256",
      },
    ],
    name: "DocumentoRegistrado",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "documentHash",
        type: "bytes32",
      },
    ],
    name: "existe",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "documentId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "documentHash",
        type: "bytes32",
      },
    ],
    name: "registrarDocumento",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b506101f68061001f6000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063092d798f1461003b578063ac2ccf8014610072575b600080fd5b61005e610049366004610185565b60009081526020819052604090205460ff1690565b604051901515815260200160405180910390f35b61008561008036600461019e565b610087565b005b806100c95760405162461bcd60e51b815260206004820152600d60248201526c4861736820696e76616c69646f60981b60448201526064015b60405180910390fd5b60008181526020819052604090205460ff16156101285760405162461bcd60e51b815260206004820152601760248201527f446f63756d656e746f207961207265676973747261646f00000000000000000060448201526064016100c0565b60008181526020819052604090819020805460ff19166001179055513390839083907ff97aa00529bbb0e6dd8e504d02a154254d497b3fff1d833505d3341876b0bae2906101799042815260200190565b60405180910390a45050565b60006020828403121561019757600080fd5b5035919050565b600080604083850312156101b157600080fd5b5050803592602090910135915056fea2646970667358221220fddce62f0911c6fa25057f92dc68e49097f70c804b39a1f8033bc925270931fb64736f6c634300081c0033";

type RegistroDocumentosConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RegistroDocumentosConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class RegistroDocumentos__factory extends ContractFactory {
  constructor(...args: RegistroDocumentosConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      RegistroDocumentos & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): RegistroDocumentos__factory {
    return super.connect(runner) as RegistroDocumentos__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RegistroDocumentosInterface {
    return new Interface(_abi) as RegistroDocumentosInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): RegistroDocumentos {
    return new Contract(address, _abi, runner) as unknown as RegistroDocumentos;
  }
}
